# Generated by Django 3.2.8 on 2021-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companyclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employclass',
            name='id',
        ),
        migrations.AddField(
            model_name='employclass',
            name='ID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employclass',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employclass',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employclass',
            name='empid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employclass',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employclass',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
